In [16]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import pickle

In [3]:
dataset = pd.read_csv('Dataset_TA.csv')

In [4]:
rtt = dataset[['rtt1','rtt2','rtt3','rtt4','rtt5','rtt6']].to_numpy()
gt_coordinates_x = dataset['gtx'].to_numpy()
gt_coordinates_y = dataset['gty'].to_numpy()
pos_id = dataset['PosId'].to_numpy()
ap1x = dataset['ap1x'].to_numpy()
ap1y = dataset['ap1y'].to_numpy()
ap2x = dataset['ap2x'].to_numpy()
ap2y = dataset['ap2y'].to_numpy()
ap3x = dataset['ap3x'].to_numpy()
ap3y = dataset['ap3y'].to_numpy()
ap4x = dataset['ap4x'].to_numpy()
ap4y = dataset['ap4y'].to_numpy()
ap5x = dataset['ap5x'].to_numpy()
ap5y = dataset['ap5x'].to_numpy()
ap6x = dataset['ap6x'].to_numpy()
ap6y = dataset['ap6x'].to_numpy()

In [5]:
X = rtt
y = pos_id

In [6]:
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
kfold = StratifiedKFold(n_splits=3, shuffle=True, random_state=750)

# Knn

In [7]:
from sklearn.neighbors import KNeighborsClassifier
results_knn = cross_val_score(KNeighborsClassifier(), X, y,cv=kfold)

C:\Users\hugos\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(("The least populated class in y has only %d"


In [8]:
print(results_knn.mean())
print(results_knn)

0.9999946599649226
[0.99999599 1.         0.99998798]


In [17]:
with open('3_fold_knn.pkl','wb') as pickle_file:
    pickle.dump(results_knn,pickle_file)

# Random Forest

In [9]:
from sklearn.ensemble import RandomForestClassifier
random_forest = RandomForestClassifier(n_estimators = 10, criterion = 'gini', random_state = 500)
results_forest = cross_val_score(random_forest, X, y,cv=kfold)

C:\Users\hugos\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(("The least populated class in y has only %d"


In [10]:
print(results_forest.mean())
print(results_forest)

0.9999946599649226
[0.99999599 1.         0.99998798]


In [18]:
with open('3_fold_forest.pkl','wb') as pickle_file:
    pickle.dump(results_forest,pickle_file)

# Decision Tree

In [11]:
from sklearn.tree import DecisionTreeClassifier
decision_tree = DecisionTreeClassifier(criterion = 'gini', random_state = 385)
results_tree = cross_val_score(decision_tree, X, y,cv=kfold)

C:\Users\hugos\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(("The least populated class in y has only %d"


In [12]:
print(results_tree.mean())
print(results_tree)

0.9999946599649226
[0.99999599 1.         0.99998798]


In [19]:
with open('3_fold_tree.pkl','wb') as pickle_file:
    pickle.dump(results_tree,pickle_file)

# Naive Bayes

In [13]:
from sklearn.naive_bayes import GaussianNB
naive_bayes= GaussianNB()
results_bayes = cross_val_score(naive_bayes, X, y,cv=kfold)

C:\Users\hugos\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(("The least populated class in y has only %d"


In [14]:
print(results_bayes.mean())
print(results_bayes)

0.9995768023471032
[0.99958748 0.99953141 0.99961151]


In [20]:
with open('3_fold_bayes.pkl','wb') as pickle_file:
    pickle.dump(results_bayes,pickle_file)